# Configuration hadolint pour notre projet RabbitMQ
ignored:
  # DL3008 - Pin versions in apt-get
  - DL3008
  # DL3018 - Pin versions in apk add
  - DL3018
  # DL4006 - Set the SHELL option
  - DL4006

# Règles de linting spécifiques
trustedRegistries:
  - docker.io
  - alpine:3.19

# Format de sortie
format: tty

# Niveau de sévérité
failure-threshold: warning